apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-nginx-config
  namespace: reactive
data:
  nginx.conf: |
    events {}

    http {
        resolver kube-dns.kube-system.svc.cluster.local valid=5s ipv6=off;

        server {
            listen 80;

            location / {
                set $backend "reactive-backend.reactive.svc.cluster.local:8000";

                proxy_pass http://$backend;
                proxy_http_version 1.1;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }