global:
  scrape_interval: 5s

scrape_configs:
  - job_name: predictive-backend
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - tasks.web-backend
        type: A
        port: 8000

  - job_name: predictive-autoscaling
    metrics_path: /metrics
    static_configs:
      - targets:
          - autoscaling:9101