events {
    worker_connections 1024;
}

http {
    upstream backend {
        server baseline-backend:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}